spring:
  application:
    name: spring-boot-data-jpa-demo

#  datasource:
#    url: jdbc:h2:file:./data3/empDB;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    username: admin
#    password: admin123

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: admin
    password: admin123

#  h2:
#    console:
#      enabled: true
#      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yaml



server:
  port: 9090
