spring:
  application:
    name: spring-boot-data-jpa-demo

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.validator.fail_fast: true

  liquibase:
    change-log: classpath:db/liquibase/changelog-master.yaml

server:
  port: 9090

---
spring:
  profiles:
    active: dev   # default profile when none is specified
